server:
  port: 1051

spring:
  active:
    profiles: local
  main:
    banner-mode: "off"
    allow-circular-references: true
    application:
      name: tokenbucket
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration/local

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true		
rate-limiter:
  token-bucket:
    users: user1,user2,user3,user4